// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsompoohqrezgzaocriu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzb21wb29ocXJlemd6YW9jcml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzQzNTksImV4cCI6MjA2MjIxMDM1OX0.iJHGY2Gmh1lSZZGZhr0uDeS44DXSjxExvp2JFSeF3AE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);